apiVersion: v1
kind: Secret
metadata:
  name: robot-dh-remote-secrets
  namespace: robot-dh
type: Opaque
stringData:
  ROBOT_DH_DB_URI: postgresql+psycopg://robot_dh_app:CHANGE_ME_APP_PASSWORD@PUBLIC_SERVER_IP_OR_DNS:5432/robot_dh
  ROBOT_DH_S3_ENDPOINT_URL: http://PUBLIC_SERVER_IP_OR_DNS:9000
  ROBOT_DH_S3_ACCESS_KEY: robotdhapp
  ROBOT_DH_S3_SECRET_KEY: CHANGE_ME_MINIO_APP_SECRET
  ROBOT_DH_S3_DATA_BUCKET: robot-datasets
  ROBOT_DH_S3_ARTIFACT_BUCKET: robot-dh-artifacts
  ROBOT_DH_REDIS_URL: redis://:CHANGE_ME_REDIS_PASSWORD@PUBLIC_SERVER_IP_OR_DNS:6379/0