listen_addresses = '*'
max_connections = 50
shared_buffers = 256MB
effective_cache_size = 1GB
work_mem = 8MB
maintenance_work_mem = 128MB
wal_level = replica
timezone = 'UTC'
log_min_duration_statement = 1000
password_encryption = scram-sha-256
