#!/bin/sh
set -euo pipefail

: "${POSTGRES_DB:?POSTGRES_DB is required}"
: "${POSTGRES_USER:?POSTGRES_USER is required}"
: "${ROBOT_DH_APP_USER:?ROBOT_DH_APP_USER is required}"
: "${ROBOT_DH_APP_PASSWORD:?ROBOT_DH_APP_PASSWORD is required}"

echo "Initializing robot-data-harness PostgreSQL roles and extensions..."

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<SQL
SELECT format('CREATE DATABASE %I OWNER %I', '${POSTGRES_DB}', '${POSTGRES_USER}')
WHERE NOT EXISTS (
  SELECT 1 FROM pg_database WHERE datname = '${POSTGRES_DB}'
)\gexec

DO \$\$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_roles WHERE rolname = '${ROBOT_DH_APP_USER}'
  ) THEN
    EXECUTE format(
      'CREATE ROLE %I LOGIN PASSWORD %L',
      '${ROBOT_DH_APP_USER}',
      '${ROBOT_DH_APP_PASSWORD}'
    );
  ELSE
    EXECUTE format(
      'ALTER ROLE %I WITH LOGIN PASSWORD %L',
      '${ROBOT_DH_APP_USER}',
      '${ROBOT_DH_APP_PASSWORD}'
    );
  END IF;
END
\$\$;

GRANT ALL PRIVILEGES ON DATABASE "${POSTGRES_DB}" TO "${ROBOT_DH_APP_USER}";
SQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
CREATE EXTENSION IF NOT EXISTS pgcrypto;

GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO "${ROBOT_DH_APP_USER}";
GRANT USAGE, CREATE ON SCHEMA public TO "${ROBOT_DH_APP_USER}";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${ROBOT_DH_APP_USER}";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${ROBOT_DH_APP_USER}";

ALTER DEFAULT PRIVILEGES FOR USER "${POSTGRES_USER}" IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO "${ROBOT_DH_APP_USER}";

ALTER DEFAULT PRIVILEGES FOR USER "${POSTGRES_USER}" IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO "${ROBOT_DH_APP_USER}";
SQL

echo "PostgreSQL initialization finished."
