#!/bin/sh
set -euo pipefail

: "${POSTGRES_DB:?POSTGRES_DB is required}"
: "${POSTGRES_USER:?POSTGRES_USER is required}"
: "${ROBOT_DH_APP_USER:?ROBOT_DH_APP_USER is required}"

POSTGRES_HBA_FILE="${POSTGRES_HBA_FILE:-${PGDATA:-/var/lib/postgresql/data}/pg_hba.conf}"
POSTGRES_APP_TRUSTED_CIDRS="${POSTGRES_APP_TRUSTED_CIDRS:-${TRUSTED_CIDR:-}}"
POSTGRES_APP_HBA_METHOD="${POSTGRES_APP_HBA_METHOD:-md5}"
MANAGED_BEGIN="# BEGIN robot-dh managed app access"
MANAGED_END="# END robot-dh managed app access"

if [ ! -f "$POSTGRES_HBA_FILE" ]; then
  echo "ERROR: pg_hba.conf not found at $POSTGRES_HBA_FILE" >&2
  exit 1
fi

tmp_hba=$(mktemp)
tmp_block=$(mktemp)
tmp_final=$(mktemp)
trap 'rm -f "$tmp_hba" "$tmp_block" "$tmp_final"' EXIT

awk -v start="$MANAGED_BEGIN" -v end="$MANAGED_END" '
  $0 == start { skip = 1; next }
  $0 == end { skip = 0; next }
  !skip { print }
' "$POSTGRES_HBA_FILE" > "$tmp_hba"

{
  printf '\n%s\n' "$MANAGED_BEGIN"
  echo "# Generated by postgres/init/02_sync_pg_hba.sh"
  if [ -n "$POSTGRES_APP_TRUSTED_CIDRS" ]; then
    for cidr in $(printf '%s\n' "$POSTGRES_APP_TRUSTED_CIDRS" | tr ',\n\t' '   '); do
      [ -n "$cidr" ] || continue
      printf 'host %s %s %s %s\n' "$POSTGRES_DB" "$ROBOT_DH_APP_USER" "$cidr" "$POSTGRES_APP_HBA_METHOD"
    done
  else
    echo "# No remote app CIDRs configured."
  fi
  printf '%s\n' "$MANAGED_END"
} > "$tmp_block"

cat "$tmp_hba" "$tmp_block" > "$tmp_final"

if cmp -s "$POSTGRES_HBA_FILE" "$tmp_final"; then
  echo "PostgreSQL pg_hba managed block already up to date."
  exit 0
fi

cat "$tmp_final" > "$POSTGRES_HBA_FILE"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres -Atqc 'SELECT pg_reload_conf();' >/dev/null

echo "Synchronized PostgreSQL pg_hba managed block in $POSTGRES_HBA_FILE."
